{{- if .Values.preInstallCheck.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-check
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  # backoffLimit: 2
  serviceAccountName: {{ include "banking-service.fullname" . }}-pvc-access-sa
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: check-pvc
          image: bitnami/kubectl:1.17
          command:
            - /bin/sh
            - -c
            - |
              echo "Checking if PVC exists"
              if kubectl get pvc {{ .Values.preInstallCheck.pvcName }} -n {{ .Values.global.namespace }}; then
                echo "PVC exists"
              else
                echo "PVC does not exist"
                exit 1
              fi
{{- end -}}