{{- if .Values.app.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "banking-service.serviceAccountName" . }}
  labels:
    {{- include "banking-service.labels" . | nindent 4 }}
  {{- with .Values.app.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.app.serviceAccount.automount }}
{{- end }}
