apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grpc-service.fullname" . }}
  labels:
    {{- include "grpc-service.labels" . | nindent 4 }}
    {{- if .Values.global.projectName }}
    project: {{ .Values.global.projectName }}
    cluster: {{ .Values.global.clusterName }}
    {{- end }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "grpc-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "grpc-service.labels" . | nindent 8 }}
        {{- if .Values.global.namespace }}
        namespace: {{ .Values.global.namespace }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.global.serviceAccount (default false .Values.global.serviceAccount.create) -}}
      serviceAccountName: {{ include "grpc-service.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.app.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          livenessProbe:
            {{- if .Values.app.livenessProbe.enabled }}
            tcpSocket:
              port: grpc
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            {{- end }}
          readinessProbe:
            {{- if .Values.app.readinessProbe.enabled }}
            tcpSocket:
              port: grpc
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          {{- with .Values.app.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.app.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
