apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grpc-server.fullname" . }}
  labels:
    {{- include "grpc-server.labels" . | nindent 4 }}
    {{- if .Values.global.projectName }}
    project: {{ .Values.global.projectName }}
    cluster: {{ .Values.global.clusterName }}
    {{- end }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "grpc-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "grpc-server.labels" . | nindent 8 }}
        {{- if .Values.global.namespace }}
        namespace: {{ .Values.global.namespace }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.app.securityContext | nindent 8 }}
      containers:
        - name: {{ include "grpc-server.fullname" . }}
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            {{- range .Values.app.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- range .Values.app.secrets }}
            - name: {{ .secretKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
            {{- end }}
          ports:
            - name: {{ .Values.app.service.name }}
              containerPort: {{ .Values.app.service.port }}
              protocol: {{ .Values.app.service.protocol }}
          
          {{- with .Values.app.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
