apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-server.fullname" . }}
  labels:
    {{- include "grpc-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TPC
      name: {{ .Values.app.service.name }}
      {{- with .Values.app.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "grpc-server.selectorLabels" . | nindent 4 }}