deploy:
  helm:
    chart: "edwynrrangel/grpc-server"
    chartVersion: "0.1.0"
  global:
    projectName: "multimedia"
    clusterName: "grpc-service"
    image:
      repository: "edwynrrangel/grpc-server"
      tag: "latest"
      pullPolicy: Always
    imagePullSecrets: 
      name: "grpc-service-multimedia-docker"
    namespace: "grpc-dev"
  app:
    secrets:
      name: "grpc-server-multimedia"  