deploy:
  helm:
    chart: "edwynrrangel/grpc-server"
    chartVersion: "0.1.0"
  global:
    projectName: "multimedia"
    clusterName: "grpc-service"
    image:
      repository: "edwynrangel"
      tag: "latest"
      pullPolicy: Always
    imagePullSecrets:
      name: "docker"
    namespace: "grpc-dev"
  secret:
    name: "grpc-server-multimedia"