name: Package Charts

on:
  push:
    paths:
      - "charts/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Packaging charts
        run: |
          echo "Packaging charts"
          echo $(pwd)
          charts_path=$(pwd)/charts/*
          echo $charts_path
          for chart in $charts_path; do
            if [ -d "$chart" ]; then
              helm package $chart --destination chart_repo/
            fi
          done
      
      - name: Update index file
        run: |
          helm repo index chart-repo --url https://edwynrrangel.github.io/grpc/chart-repo

      - name: Get author info
        id: get_author
        run: |
          echo "author_name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "author_email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

      - name: Print author info
        run: |
          echo "The author name is $author_name"
          echo "The author email is $author_email"

      - name: Commit and push chart packages and index file
        run: |
          git config --local --replace-all user.email "${{ env.author_email }}"
          git config --local --replace-all user.name "${{ env.author_name }}"
          git add chart-repo/
          git commit -m "Update chart repository" -a || echo "No changes to commit"
          git push https://${{ secrets.PAT_SECRET }}@github.com/edwynrrangel/grpc.git HEAD:main
        

   
