name: Package Charts

on:
  push:
    paths:
      - "charts/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Packaging charts
        run: |
          echo "Packaging charts"
          echo $(pwd)
          charts_path=$(pwd)/charts/*
          echo $charts_path
          for chart in $charts_path; do
            if [ -d "$chart" ]; then
              helm package $chart --destination chart_repo/
            fi
          done

      - name: Get author info
        id: get_author
        run: |
          echo "author_name=$(git log -1 --pretty=format:'%an')"
          echo "author_email=$(git log -1 --pretty=format:'%ae')"

      - name: Print author info
        run: |
          echo "The author name is ${{ steps.get_author.outputs.author_name }}"
          echo "The author email is ${{ steps.get_author.outputs.author_email }}"
        

   
