name: Charts Package 

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      
      - name: Packaging charts
        run: |
          echo "Packaging charts"
          mkdir -p chart-repo
          charts_path=$(pwd)/charts/*
          for chart in $charts_path; do
            if [ -d "$chart" ]; then
              helm package $chart --destination chart-repo/
            fi
          done
      
      - name: Update index file
        run: |
          helm repo index chart-repo --url https://edwynrrangel.github.io/charts/

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: chart-packages
          path: chart-repo/
    
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH for GitHub Access
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: chart-packages
          path: chart-repo/

      - name: Get author info
        id: get_author
        run: |
          echo "author_name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "author_email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV
      
      - name: Clone charts repository
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          echo $(ssh -T git@github.com)
          git clone git@github.com:edwynrrangel/charts.git 

      - name: Copy chart packages to charts repository
        run: |
          cp chart-repo/* charts/
          ls -la charts/
      
      - name: Push chart packages to charts repository
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          echo $(ssh -T git@github.com)
          cd charts
          git config --local --replace-all user.email "$author_email"
          git config --local --replace-all user.name "$author_name"
          git add .
          git commit -m "Update charts repository by $author_email" -a || echo "No changes to commit"
          git branch -M master
          git push origin HEAD:master