name: Package Charts

on:
  push:
    paths:
      - "charts/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      
      - name: Packaging charts
        run: |
          echo "Packaging charts"
          echo $(pwd)
          charts_path=$(pwd)/charts/*
          echo $charts_path
          for chart in $charts_path; do
            if [ -d "$chart" ]; then
              helm package $chart --destination chart_repo/
            fi
          done
      
      - name: Update index file
        run: |
          helm repo index chart-repo --url https://edwynrrangel.github.io/charts/

      - name: Get author info
        id: get_author
        run: |
          echo "author_name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "author_email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

      - name: Print author info
        run: |
          echo "The author name is $author_name"
          echo "The author email is $author_email"

      - name: Commit and push chart packages and index file
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          git config --global user.email "$author_email"
          git config --global user.name "$author_name"
          git config --global --list
          ssh -Tv git@github.com
          # if git remote | grep -q deploy; then
          #   git remote remove deploy
          # fi
          # git remote add deploy git@github.com:edwynrrangel/charts.git
          # git branch -M master
          # git config --local --replace-all user.email "$author_email"
          # git config --local --replace-all user.name "$author_name"
          # git config --local --list
          # git add chart-repo/
          # git commit -m "Update chart repository" -a || echo "No changes to commit"
          # git push deploy HEAD:master
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

        

   
