name: Charts Package

on:
  push:
    paths:
      - "charts/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package charts
        run: |
          charts_path=$(pwd)/charts
          echo $charts_path
          for chart in $charts_path; do
            if [ -d "$chart" ]; then
              helm package $chart --destination chart_repo/
            fi
          done
        

   
