name: Deploy Go

on:
  push:
    branches:
      - master
    paths:
      - "go/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push image
        run: |
          DIRECTORY_NAME=$(git diff --name-only HEAD^ HEAD | grep '^go/' | cut -d '/' -f 2 | uniq)
          if [ -z "$DIRECTORY_NAME" ]; then
            echo "No changes in 'go/' directories"
            exit 1
          fi
          echo "Building image for directory: $DIRECTORY_NAME"
          docker build -t $username/$DIRECTORY_NAME:latest -f k8s/Dockerfile .
          docker push $username/$DIRECTORY_NAME:latest
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      