name: Deploy Go

on:
  push:
    branches:
      - master
    paths:
      - "go/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Print Credentials
        run: |
          echo "Docker Username: $username"
          echo "Docker Password: $password"
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      