name: Deploy Go

on:
  push:
    branches:
      - master
    paths:
      - "go/**"
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Enter the directory name under go/ to build and push'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      base_path: ${{ steps.set_path.outputs.base_path }}
      release_name: ${{ steps.set_project_name.outputs.release_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set path
        id: set_path
        run: |
          echo "base_path=go" >> $GITHUB_OUTPUT

      - name: Set Project Name
        id: set_project_name
        run: |
          if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            release_name=$(git diff --name-only HEAD^ HEAD | grep '^go/' | cut -d '/' -f 2 | uniq)
          else
            release_name="${{ github.event.inputs.release_name }}"
          fi
          echo "release_name=$release_name" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push image
        run: |
          echo "Building image for directory: $base_path/$release_name"
          cd $base_path/$release_name
          docker build -t $username/$release_name:latest --no-cache -f ./k8s/Dockerfile .
          docker push $username/$release_name:latest
        env:
          base_path: ${{ needs.setup.outputs.base_path }}
          release_name: ${{ needs.setup.outputs.release_name }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      
  deploy:
    needs: [setup, build]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables from YAML
        uses: edwynrrangel/github-actions-suite/actions/yaml-to-env@master
        with:
          yaml-file: ${{ needs.setup.outputs.base_path }}/${{ needs.setup.outputs.release_name }}/k8s/config.yaml

      - name: Replace tokens in YAML
        uses: edwynrrangel/github-actions-suite/actions/replace-tokens@master
        with:
          input-yaml-file: ${{ needs.setup.outputs.base_path }}/${{ needs.setup.outputs.release_name }}/k8s/values.yaml

      - name: Deploy to Kubernetes
        run: |
          echo "Deploying image for directory: $base_path/$release_name"
          helm upgrade $release_name $DEPLOY_HELM_CHART \
            --version $DEPLOY_HELM_CHART_VERSION \
            --install \
            --namespace $DEPLOY_GLOBAL_NAMESPACE \
            --create-namespace \
            --debug \
            -f ./$base_path/$release_name/k8s/values.yaml
        env:
          base_path: ${{ needs.setup.outputs.base_path }}
          release_name: ${{ needs.setup.outputs.release_name }}
      