name: Deploy IaC

on:
  push:
    branches:
      - master
    paths:
      - "iac/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        run: |
          echo "Update repository for Helm"
          helm repo update
          echo "Run Terraform"
          cd iac/
          terraform init -upgrade
          terraform apply -auto-approve
        env:
          TF_VAR_minio_user: ${{ secrets.MINIO_USER }}
          TF_VAR_minio_password: ${{ secrets.MINIO_PASSWORD }}
          TF_VAR_multimedia_readonly_user_secret: ${{ secrets.MULTIMEDIA_READONLY_USER_SECRET }}
