name: Deploy IaC

on:
  push:
    branches:
      - master
    paths:
      - "iac/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        run: |
          echo "Update repository for Helm"
          helm repo update
          echo "Run Terraform"
          cd iac/
          terraform init
          terraform apply -auto-approve
