name: Deploy Go

on:
  push:
    branches:
      - master
    paths:
      - "go/**"
  workflow_dispatch:
    inputs:
      directoryName:
        description: 'Enter the directory name under go/ to build and push'
        required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push image
        run: |
          if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            DIRECTORY_NAME=$(git diff --name-only HEAD^ HEAD | grep '^go/' | cut -d '/' -f 2 | uniq)
          else
            DIRECTORY_NAME="${{ github.event.inputs.directoryName }}"
          fi
          echo "Building image for directory: $DIRECTORY_NAME"
          cd go/$DIRECTORY_NAME
          ls -l
          docker build -t $username/$DIRECTORY_NAME:latest --no-cache -f ./k8s/Dockerfile .
          docker push $username/$DIRECTORY_NAME:latest
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      
      - name: Deploy to Kubernetes
        run: |
          if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            DIRECTORY_NAME=$(git diff --name-only HEAD^ HEAD | grep '^go/' | cut -d '/' -f 2 | uniq)
          else
            DIRECTORY_NAME="${{ github.event.inputs.directoryName }}"
          fi
          echo "Deploying image for directory: $DIRECTORY_NAME"
          helm install $HELM_CHART --namespace HELM_NAMESPACE --create-namespace --debug --name-template $DIRECTORY_NAME -f ./$DIRECTORY_NAME/k8s/values.yaml
        env:
          HELM_CHART: ${{ secrets.HELM_CHART }}
          HELM_NAMESPACE: ${{ secrets.HELM_NAMESPACE }}

      