name: Deploy Helm Chart to GitHub Pages

on:
  push:
    branches: ["master"]
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Package Helm Chart
        run: |
          mkdir -p chart-repo
          for dir in charts/*; do
            if [ -d "$dir" ]; then
              helm package "$dir" --destination chart-repo
            fi
          done
          helm repo index chart-repo --url https://edwynrrangel.github.io/grpc/chart-repo

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'chart-repo'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
