name: Publish Chart

on:
  push:
    paths:
      - "chart-repo/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH for GitHub Access
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get author info
        id: get_author
        run: |
          echo "author_name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "author_email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

      - name: Print author info
        run: |
          echo "The author name is $author_name"
          echo "The author email is $author_email"

      - name: Clone charts repository
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          echo $(ssh -T git@github.com)
          git clone git@github.com:edwynrrangel/charts.git temp_charts_repo

      - name: Copy chart packages to charts repository
        run: |
          mkdir -p temp_charts_repo
          cp chart-repo/* temp_charts_repo/
          ls -la temp_charts_repo/
      
      - name: Push chart packages to charts repository
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          echo $(ssh -T git@github.com)
          cd temp_charts_repo
          git config --local --replace-all user.email "$author_email"
          git config --local --replace-all user.name "$author_name"
          git add .
          git commit -m "Update chart repository" -a || echo "No changes to commit"
          git branch -M master
          git push origin HEAD:master
